import type { SidebarGroup } from './docs-metadata.model';

export const SIDEBAR_GROUPS: SidebarGroup[] = [
	{
		label: 'Getting Started',
		order: 1,
		items: [
			{ title: 'Overview', slug: 'overview', group: 'Getting Started', order: 1, since: '0.0.1', tags: [], description: 'Introduction to Quenetiq' },
			{ title: 'Getting Started', slug: 'getting-started', group: 'Getting Started', order: 2, since: '0.0.1', tags: ['install', 'setup'], description: 'Quick start guide' },
		],
	},
	{
		label: 'Core',
		order: 2,
		items: [
			{ title: '@quenetiq/client', slug: 'client', group: 'Core', order: 1, since: '0.0.1', tags: ['client', 'graphql'], description: 'Framework-agnostic GraphQL client', package: '@quenetiq/client',
				children: [
					{ title: 'createClient', slug: 'client-create', group: 'Core', order: 1, since: '0.0.1', tags: ['client', 'create', 'factory'], description: 'Create and configure QuenetiqClient' },
					{ title: 'Query & Mutate', slug: 'client-operations', group: 'Core', order: 2, since: '0.0.1', tags: ['client', 'query', 'mutate'], description: 'Execute queries and mutations' },
					{ title: 'Middleware', slug: 'client-middleware', group: 'Core', order: 3, since: '0.0.1', tags: ['client', 'middleware'], description: 'Middleware pipeline for requests' },
					{ title: 'Streaming', slug: 'client-streaming', group: 'Core', order: 4, since: '0.0.1', tags: ['client', 'streaming', 'defer'], description: '@defer/@stream incremental delivery' },
					{ title: 'File Upload', slug: 'client-upload', group: 'Core', order: 5, since: '0.0.1', tags: ['client', 'upload', 'multipart'], description: 'Multipart file upload support' },
					{ title: 'Val', slug: 'client-val', group: 'Core', order: 6, since: '0.0.1', tags: ['client', 'val', 'null-handling'], description: 'Value container with null handling' },
				],
			},
			{ title: '@quenetiq/core', slug: 'core', group: 'Core', order: 2, since: '0.0.1', tags: ['angular', 'core'], description: 'Angular-native GraphQL integration', package: '@quenetiq/core',
				children: [
					{ title: 'Cache Writes', slug: 'cache-writes', group: 'Core', order: 1, since: '1.0.0', tags: ['core', 'cache', 'write'], description: 'Injectable cache write helpers' },
					{ title: 'Glob Invalidation', slug: 'glob-invalidation', group: 'Core', order: 2, since: '1.0.0', tags: ['core', 'cache', 'glob'], description: 'Glob-pattern cache invalidation' },
					{ title: 'Mutation Batching', slug: 'mutation-batching', group: 'Core', order: 3, since: '1.0.0', tags: ['core', 'mutation', 'batch'], description: 'Mutation batching service' },
					{ title: 'Conditional Queries', slug: 'skip-query', group: 'Core', order: 4, since: '1.0.0', tags: ['core', 'query', 'skip'], description: 'Conditionally skip query execution' },
					{ title: 'Null Detection', slug: 'null-detection', group: 'Core', order: 5, since: '1.0.5', tags: ['core', 'null', 'overlay'], description: 'Null detection service and overlay' },
					{ title: 'Response Diff', slug: 'response-diff', group: 'Core', order: 6, since: '1.0.0', tags: ['core', 'diff', 'logging'], description: 'Response diff logging utility' },
					{ title: 'Endpoint Decorator', slug: 'use-endpoint', group: 'Core', order: 7, since: '1.0.0', tags: ['core', 'endpoint', 'decorator'], description: 'Named endpoint decorator and resolvers' },
					{ title: 'Endpoint Discovery', slug: 'endpoint-discovery', group: 'Core', order: 8, since: '1.0.0', tags: ['core', 'endpoint', 'discovery'], description: 'Auto-discover endpoint schemas' },
					{ title: 'Endpoint Mocking', slug: 'endpoint-mock', group: 'Core', order: 9, since: '1.0.0', tags: ['core', 'endpoint', 'mock'], description: 'Schema-aware endpoint mocking' },
					{ title: 'Subscriptions (multi)', slug: 'subscribe-multi', group: 'Core', order: 10, since: '1.0.0', tags: ['core', 'subscription', 'websocket'], description: 'Multi-endpoint WebSocket subscriptions' },
					{ title: 'Infer Types', slug: 'infer-types', group: 'Core', order: 11, since: '1.0.0', tags: ['core', 'types', 'inference'], description: 'Type inference utilities' },
					{ title: 'Streaming', slug: 'core-streaming', group: 'Core', order: 12, since: '1.0.6-beta', tags: ['core', 'streaming', 'defer'], description: 'provideStreaming() and queryStream()' },
					{ title: 'Use Decorators', slug: 'use-decorators', group: 'Core', order: 13, since: '1.0.6-beta', tags: ['core', 'decorators', 'query', 'mutation', 'subscription'], description: '@UseQuery, @UseMutation, @UseSubscription class decorators' },
				],
			},
			{ title: '@quenetiq/cache', slug: 'cache', group: 'Core', order: 3, since: '0.0.1', tags: ['cache', 'normalized'], description: 'Normalized cache with type policies', package: '@quenetiq/cache',
				children: [
					{ title: 'Normalized Cache', slug: 'normalized-cache', group: 'Core', order: 1, since: '0.0.1', tags: ['cache', 'normalized'], description: 'Low-level entity store' },
					{ title: 'CacheService', slug: 'cache-service', group: 'Core', order: 2, since: '0.0.1', tags: ['cache', 'angular'], description: 'Angular wrapper for CacheStore' },
					{ title: 'Garbage Collection', slug: 'cache-gc', group: 'Core', order: 3, since: '0.0.1', tags: ['cache', 'gc'], description: 'Reference counting and TTL eviction' },
					{ title: 'Type Policies', slug: 'type-policies', group: 'Core', order: 4, since: '0.0.1', tags: ['cache', 'type-policies'], description: 'Custom merge and key strategies' },
					{ title: 'Optimistic Updates', slug: 'optimistic-updates', group: 'Core', order: 5, since: '0.0.1', tags: ['cache', 'optimistic'], description: 'Key-level optimistic updates' },
					{ title: 'Local State', slug: 'local-state', group: 'Core', order: 6, since: '0.0.1', tags: ['cache', 'local-state'], description: 'UI-local state in cache' },
					{ title: 'Cache Metrics', slug: 'cache-metrics', group: 'Core', order: 7, since: '0.0.1', tags: ['cache', 'metrics'], description: 'Cache performance metrics' },
					{ title: 'Cache Events', slug: 'cache-events', group: 'Core', order: 8, since: '0.0.1', tags: ['cache', 'events'], description: 'Cache event system' },
					{ title: 'Cross-Tab Sync', slug: 'cross-tab-sync', group: 'Core', order: 9, since: '0.0.1', tags: ['cache', 'sync'], description: 'Cross-tab cache synchronization' },
					{ title: 'Smart Persistence', slug: 'smart-persistence', group: 'Core', order: 10, since: '0.0.1', tags: ['cache', 'persistence'], description: 'Entity-level persistence with TTL' },
					{ title: 'Cache Persistence', slug: 'cache-persistence', group: 'Core', order: 11, since: '0.0.1', tags: ['cache', 'persistence'], description: 'localStorage persistence layer' },
					{ title: 'Cache Migration', slug: 'cache-migration', group: 'Core', order: 12, since: '1.0.0', tags: ['cache', 'migration'], description: 'Version migration for cached data' },
					{ title: 'Cache Helpers', slug: 'cache-helpers', group: 'Core', order: 13, since: '0.0.1', tags: ['cache', 'helpers', 'keys', 'meta', 'snapshot', 'optimistic'], description: 'Standalone cache helper functions' },
				],
			},
			{ title: '@quenetiq/observables', slug: 'observables', group: 'Core', order: 4, since: '1.0.6-beta', tags: ['observables', 'rxjs', 'cache'], description: 'RxJS operators for cache observation', package: '@quenetiq/observables',
				children: [
					{ title: 'observeEntity', slug: 'observe-entity', group: 'Core', order: 1, since: '1.0.6-beta', tags: ['observables', 'entity', 'watch'], description: 'Watch a single cache entity' },
					{ title: 'observeQuery', slug: 'observe-query', group: 'Core', order: 2, since: '1.0.6-beta', tags: ['observables', 'query', 'watch'], description: 'Watch a cached query result' },
					{ title: 'cacheFirst', slug: 'cache-first', group: 'Core', order: 3, since: '1.0.6-beta', tags: ['observables', 'cache-first'], description: 'Cache-first strategy with network fetch' },
					{ title: 'staleWhileRevalidate', slug: 'stale-while-revalidate', group: 'Core', order: 4, since: '1.0.6-beta', tags: ['observables', 'swr'], description: 'Stale-while-revalidate strategy' },
					{ title: 'watchQuery', slug: 'watch-query', group: 'Core', order: 5, since: '1.0.6-beta', tags: ['observables', 'watch', 'query'], description: 'Combined fetch + cache observation' },
					{ title: 'asCache', slug: 'as-cache', group: 'Core', order: 6, since: '1.0.6-beta', tags: ['observables', 'cache', 'reader'], description: 'Reactive cache reader' },
					{ title: 'invalidateOn', slug: 'invalidate-on', group: 'Core', order: 7, since: '1.0.6-beta', tags: ['observables', 'invalidation', 'operator'], description: 'Pipeable invalidation operator' },
				],
			},
			{ title: 'Multi-Endpoint', slug: 'endpoints', group: 'Core', order: 5, since: '1.0.0', tags: ['endpoints', 'multi-endpoint', 'yaml', 'fallback'], description: 'Multi-endpoint YAML config, fallback routing, health checks', package: '@quenetiq/core', children: [] },
		],
	},
	{
		label: 'Frameworks',
		order: 3,
		items: [
			{ title: '@quenetiq/react', slug: 'react', group: 'Frameworks', order: 1, since: '0.0.1', tags: ['react', 'hooks'], description: 'React hooks and components', package: '@quenetiq/react',
				children: [
					{ title: 'useQuery', slug: 'react-use-query', group: 'Frameworks', order: 1, since: '0.0.1', tags: ['react', 'query'], description: 'Reactive query hook' },
					{ title: 'useMutation', slug: 'react-use-mutation', group: 'Frameworks', order: 2, since: '0.0.1', tags: ['react', 'mutation'], description: 'Mutation hook with optimistic updates' },
					{ title: 'useSubscription', slug: 'react-use-subscription', group: 'Frameworks', order: 3, since: '0.0.1', tags: ['react', 'subscription'], description: 'WebSocket subscription hook' },
					{ title: 'useFragment', slug: 'react-use-fragment', group: 'Frameworks', order: 4, since: '0.0.1', tags: ['react', 'fragment'], description: 'Fragment cache read hook' },
					{ title: 'useLiveQuery', slug: 'react-live-query', group: 'Frameworks', order: 5, since: '0.0.2-alpha.1', tags: ['react', 'live', 'realtime'], description: 'Real-time query + subscription hook' },
					{ title: 'Suspense & SSR', slug: 'react-suspense', group: 'Frameworks', order: 6, since: '0.0.1', tags: ['react', 'suspense', 'ssr'], description: 'Suspense and SSR hooks' },
					{ title: 'Components', slug: 'react-components', group: 'Frameworks', order: 7, since: '0.0.1', tags: ['react', 'components'], description: 'RateLimitGate and render-prop components' },
					{ title: 'useVal', slug: 'react-val', group: 'Frameworks', order: 8, since: '0.0.1', tags: ['react', 'val'], description: 'Reactive value hook with null handling' },
					{ title: 'Streaming', slug: 'react-streaming', group: 'Frameworks', order: 9, since: '1.0.6-beta', tags: ['react', 'streaming', 'defer'], description: 'useStreamQuery hook for @defer/@stream' },
				],
			},
			{ title: '@quenetiq/vue', slug: 'vue', group: 'Frameworks', order: 2, since: '0.0.1', tags: ['vue', 'composables'], description: 'Vue composables and plugin', package: '@quenetiq/vue',
				children: [
					{ title: 'useQuery', slug: 'vue-use-query', group: 'Frameworks', order: 1, since: '0.0.1', tags: ['vue', 'query'], description: 'Reactive query composable' },
					{ title: 'useMutation', slug: 'vue-use-mutation', group: 'Frameworks', order: 2, since: '0.0.1', tags: ['vue', 'mutation'], description: 'Mutation composable with optimistic updates' },
					{ title: 'useSubscription', slug: 'vue-use-subscription', group: 'Frameworks', order: 3, since: '0.0.1', tags: ['vue', 'subscription'], description: 'WebSocket subscription composable' },
					{ title: 'useFragment', slug: 'vue-use-fragment', group: 'Frameworks', order: 4, since: '0.0.1', tags: ['vue', 'fragment'], description: 'Fragment cache read composable' },
					{ title: 'useLiveQuery', slug: 'vue-live-query', group: 'Frameworks', order: 5, since: '0.0.2-alpha.1', tags: ['vue', 'live', 'realtime'], description: 'Real-time query + subscription composable' },
					{ title: 'Suspense & SSR', slug: 'vue-suspense', group: 'Frameworks', order: 6, since: '0.0.1', tags: ['vue', 'suspense', 'ssr'], description: 'Suspense and SSR composables' },
					{ title: 'Directives', slug: 'vue-directives', group: 'Frameworks', order: 7, since: '0.0.1', tags: ['vue', 'directives'], description: 'v-qtq-mutate and v-qtq-loading directives' },
					{ title: 'useVal', slug: 'vue-val', group: 'Frameworks', order: 8, since: '0.0.1', tags: ['vue', 'val'], description: 'Reactive value composable with null handling' },
					{ title: 'Streaming', slug: 'vue-streaming', group: 'Frameworks', order: 9, since: '1.0.6-beta', tags: ['vue', 'streaming', 'defer'], description: 'useStreamQuery composable for @defer/@stream' },
				],
			},
		],
	},
	{
		label: 'Features',
		order: 4,
		items: [
			{ title: 'Subscriptions', slug: 'subscriptions', group: 'Features', order: 1, since: '0.0.1', tags: ['subscriptions', 'websocket'], description: 'WebSocket subscriptions', package: '@quenetiq/subscriptions',
				children: [
					{ title: 'WsClient', slug: 'ws-client', group: 'Features', order: 1, since: '0.0.1', tags: ['subscriptions', 'websocket', 'client'], description: 'Multiplexed WebSocket client' },
					{ title: 'GraphQL Subscription', slug: 'graphql-subscription', group: 'Features', order: 2, since: '0.0.1', tags: ['subscriptions', 'graphql'], description: 'Basic GraphQL subscription client' },
				],
			},
			{ title: 'Live Queries', slug: 'live-queries', group: 'Features', order: 2, since: '0.0.2-alpha.1', tags: ['live', 'realtime'], description: 'Real-time live queries', children: [] },
			{ title: 'File Upload', slug: 'file-upload', group: 'Features', order: 3, since: '0.0.1', tags: ['upload', 'multipart'], description: 'Multipart file upload', package: '@quenetiq/file-upload', children: [] },
			{ title: 'Pagination', slug: 'pagination', group: 'Features', order: 4, since: '0.0.1', tags: ['pagination', 'offset', 'cursor'], description: 'Offset and cursor pagination', package: '@quenetiq/pagination',
				children: [
					{ title: 'Offset Pagination', slug: 'offset-pagination', group: 'Features', order: 1, since: '0.0.1', tags: ['pagination', 'offset'], description: 'Offset-based pagination' },
					{ title: 'Cursor Pagination', slug: 'cursor-pagination', group: 'Features', order: 2, since: '0.0.1', tags: ['pagination', 'cursor'], description: 'Cursor-based pagination' },
				],
			},
			{ title: 'Fragments', slug: 'fragments', group: 'Features', order: 5, since: '0.0.1', tags: ['fragments', 'composable'], description: 'Fragment composition and data masking', package: '@quenetiq/fragments',
				children: [
					{ title: 'Fragment Composition', slug: 'fragment-composition', group: 'Features', order: 1, since: '0.0.1', tags: ['fragments', 'composition'], description: 'Fragment composition and data masking' },
				],
			},
			{ title: 'Persisted Queries', slug: 'persisted-queries', group: 'Features', order: 6, since: '0.0.1', tags: ['apq', 'persisted'], description: 'Automatic Persisted Queries', package: '@quenetiq/persisted-queries', children: [] },
			{ title: 'SSR', slug: 'ssr', group: 'Features', order: 7, since: '0.0.1', tags: ['ssr', 'server-side'], description: 'Server-Side Rendering helpers', package: '@quenetiq/ssr', children: [] },
			{ title: 'Epic Fetus', slug: 'epic-fetus', group: 'Features', order: 8, since: '1.0.5', tags: ['null-detection', 'overlay'], description: 'Null detection overlay', children: [] },
		],
	},
	{
		label: 'Middleware',
		order: 5,
		items: [
			{ title: 'Middleware Overview', slug: 'middlewares', group: 'Middleware', order: 1, since: '0.0.1', tags: ['middleware', 'pipeline'], description: 'Composable middleware pipeline', package: '@quenetiq/middlewares',
				children: [
					{ title: 'Auth Refresh', slug: 'auth-refresh', group: 'Middleware', order: 1, since: '0.0.1', tags: ['middleware', 'auth', 'refresh'], description: 'Automatic auth token refresh middleware' },
					{ title: 'Retry Exchange', slug: 'retry-exchange', group: 'Middleware', order: 2, since: '0.0.1', tags: ['middleware', 'retry', 'backoff'], description: 'Retry with exponential backoff' },
					{ title: 'Offline Queue', slug: 'offline-queue', group: 'Middleware', order: 3, since: '0.0.1', tags: ['middleware', 'offline', 'queue'], description: 'Offline mutation queue' },
					{ title: 'Auto Mock', slug: 'auto-mock', group: 'Middleware', order: 4, since: '0.0.1', tags: ['middleware', 'mock', 'testing'], description: 'Schema-aware auto mocking middleware' },
					{ title: 'Rate Limit', slug: 'rate-limit', group: 'Middleware', order: 5, since: '0.0.1', tags: ['middleware', 'rate-limit'], description: 'Client-side rate limiting' },
					{ title: 'Dedup Middleware', slug: 'dedup-middleware', group: 'Middleware', order: 6, since: '0.0.1', tags: ['middleware', 'dedup'], description: 'Request deduplication middleware' },
					{ title: 'Cost Estimation', slug: 'cost-estimation', group: 'Middleware', order: 7, since: '0.0.1', tags: ['middleware', 'cost', 'query-complexity'], description: 'Query cost estimation and blocking' },
					{ title: 'Focus Refetch', slug: 'focus-refetch', group: 'Middleware', order: 8, since: '0.0.1', tags: ['middleware', 'refetch', 'focus'], description: 'Refetch on window focus' },
				],
			},
			{ title: 'Error Handling', slug: 'errors', group: 'Middleware', order: 2, since: '0.0.3', tags: ['errors', 'handler'], description: 'Typed error classes and handler', package: '@quenetiq/errors', children: [] },
			{ title: 'OpenTelemetry', slug: 'opentelemetry', group: 'Middleware', order: 3, since: '1.0.5', tags: ['otel', 'tracing'], description: 'W3C Trace Context propagation', package: '@quenetiq/opentelemetry', children: [] },
		],
	},
	{
		label: 'Tools',
		order: 6,
		items: [
			{ title: 'Codegen', slug: 'codegen', group: 'Tools', order: 1, since: '0.0.1', tags: ['codegen', 'cli'], description: 'CLI code generation', package: '@quenetiq/codegen', children: [] },
			{ title: 'Dev Server', slug: 'dev-server', group: 'Tools', order: 2, since: '0.0.3', tags: ['dev-server', 'mock'], description: 'Unified development server', package: '@quenetiq/dev-server', children: [] },
			{ title: 'Downloader', slug: 'downloader', group: 'Tools', order: 3, since: '0.0.1', tags: ['schema', 'download'], description: 'Schema introspection download', package: '@quenetiq/downloader', children: [] },
			{ title: 'Testing', slug: 'testing', group: 'Tools', order: 4, since: '0.0.1', tags: ['testing', 'mock'], description: 'Mock GraphQL backend for tests', package: '@quenetiq/testing', children: [] },
			{ title: 'Debugging', slug: 'debugging', group: 'Tools', order: 5, since: '0.0.1', tags: ['debugging', 'devtools'], description: 'Debugging and inspection utilities', package: '@quenetiq/debugging', children: [] },
			{ title: 'ESLint Plugin', slug: 'eslint-plugin', group: 'Tools', order: 6, since: '1.0.6-beta', tags: ['eslint', 'lint', 'gql', 'rules'], description: 'GraphQL lint rules for gql templates', package: '@quenetiq/eslint-plugin-gql', children: [] },
		],
	},
	{
		label: 'Reference',
		order: 7,
		items: [
			{ title: 'API Reference', slug: 'api', group: 'Reference', order: 1, since: '0.0.1', tags: ['api', 'reference'], description: 'Complete API reference' },
			{ title: 'Comparison', slug: 'comparison', group: 'Reference', order: 2, since: '0.0.1', tags: ['comparison', 'apollo', 'relay'], description: 'Comparison with other solutions' },
			{ title: 'Migration', slug: 'migration', group: 'Reference', order: 3, since: '0.0.2-alpha.1', tags: ['migration', 'apollo'], description: 'Migration from Apollo', children: [] },
			{ title: 'Apollo Adapter', slug: 'apollo-adapter', group: 'Reference', order: 4, since: '0.0.3', tags: ['apollo', 'adapter'], description: 'Apollo Client migration adapter', package: '@quenetiq/apollo-adapter', children: [] },
		],
	},
	{
		label: 'Environment',
		order: 8,
		items: [
			{ title: 'Sandboxes', slug: 'devcontainers', group: 'Environment', order: 1, since: '0.0.1', tags: ['codespaces', 'stackblitz'], description: 'Online development environments' },
		],
	},
];
