import { Component, signal } from '@angular/core';

// These types would normally be auto-generated by @quenetiq/codegen
interface GetNotesQuery {
  getNotes: Array<{ id: string; title: string; content: string }>;
}

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <h1>@quenetiq/codegen</h1>
    <p>Auto-generate TypeScript types from your GraphQL schema.</p>
    <p>This starter shows generated types in action:</p>
    <pre><code>interface GetNotesQuery &#123;
  getNotes: Array&lt;&#123; id: string; title: string; content: string &#125;&gt;;
&#125;</code></pre>
    <p><em>Run <code>npx quenetiq-codegen</code> to generate types from your schema.</em></p>
  `,
})
export class AppComponent {}
