import { readFileSync, existsSync } from 'fs';
import {
	parse,
	type DocumentNode,
	type FragmentDefinitionNode,
	type FieldNode,
	type SelectionNode,
	type InlineFragmentNode,
} from 'graphql';

export interface ParsedFragment {
	name: string;
	typeCondition: string;
	fields: string[];
	inlineFragments: string[];
	inlineFragmentFields: Record<string, string[]>;
	document: string;
	filePath: string;
}

export function parseFragmentFile(filePath: string): ParsedFragment[] | null {
	if (!existsSync(filePath)) return null;

	const content = readFileSync(filePath, 'utf-8').trim();
	if (!content) return null;

	let doc: DocumentNode;
	try {
		doc = parse(content);
	} catch {
		return null;
	}

	const fragments: ParsedFragment[] = [];

	for (const def of doc.definitions) {
		if (def.kind !== 'FragmentDefinition') continue;
		const f = def as FragmentDefinitionNode;
		const name = f.name?.value;
		if (!name) continue;

		const fields: string[] = [];
		const inlineFragments: string[] = [];
		const inlineFragmentFields: Record<string, string[]> = {};

		for (const sel of f.selectionSet.selections) {
			collectFieldInfo(sel, fields, inlineFragments, inlineFragmentFields);
		}

		fragments.push({
			name,
			typeCondition: f.typeCondition.name.value,
			fields,
			inlineFragments,
			inlineFragmentFields,
			document: content,
			filePath,
		});
	}

	return fragments.length > 0 ? fragments : null;
}

function collectFieldInfo(
	sel: SelectionNode,
	fields: string[],
	inlineFragments: string[],
	inlineFragmentFields: Record<string, string[]> = {},
	currentType?: string,
): void {
	if (sel.kind === 'Field') {
		const f = sel as FieldNode;
		if (f.name.value.startsWith('__')) return;
		fields.push(f.name.value);
		if (currentType) {
			(inlineFragmentFields[currentType] ??= []).push(f.name.value);
		}
	} else if (sel.kind === 'InlineFragment') {
		const inf = sel as InlineFragmentNode;
		if (inf.typeCondition) {
			const typeName = inf.typeCondition.name.value;
			inlineFragments.push(typeName);
			for (const s of inf.selectionSet.selections) {
				collectFieldInfo(s, fields, inlineFragments, inlineFragmentFields, typeName);
			}
		}
	} else if (sel.kind === 'FragmentSpread') {
		// referenced by name — caller can resolve separately
	}
}

export function generateFragmentCode(fragments: ParsedFragment[], typesCode?: string, clientPreset?: boolean): string {
	const lines: string[] = ['// Auto-generated by @quenetiq/codegen. DO NOT EDIT.\n'];

	lines.push('type PickSafe<T, K extends string> = Pick<T, Extract<keyof T, K>>;\n');

	if (clientPreset) {
		lines.push('import { createTypedQuery, type TypedQueryString, type FragmentRef } from "@quenetiq/core";\n');
	} else {
		lines.push('import { gql, type TypedDocumentNode, type FragmentRef } from "@quenetiq/core";\n');
	}

	const typeNames = typesCode ? extractTypeNames(typesCode) : [];

	if (typeNames.length > 0) {
		lines.push('import type {');
		typeNames.forEach((t) => lines.push(`  ${t},`));
		lines.push('} from "../types";\n');
	}

	for (const f of fragments) {
		const resultName = `${f.name}Fragment`;
		const keyName = `${f.name}Fragment\$key`;
		const typeName = f.typeCondition;

		lines.push(`export type ${resultName} = PickSafe<${typeName}, '${f.fields.join('\' | \'')}'>;`);
		lines.push('');

		const hasInline = f.inlineFragments.length > 0;
		if (hasInline) {
			lines.push(`export type ${resultName}WithInline = ${resultName} & (`);
			const parts = f.inlineFragments.map((t) => {
				const inlineFields = f.inlineFragmentFields[t];
				if (inlineFields && inlineFields.length > 0) {
					return `  { __typename: '${t}' } & PickSafe<${t}, '${inlineFields.join('\' | \'')}'>`;
				}
				return `  { __typename: '${t}' }`;
			});
			lines.push(parts.join(' | '));
			lines.push(');');
			lines.push('');
		}

		lines.push(`export type ${keyName} = FragmentRef<${resultName}, '${f.name}'>;`);
		lines.push('');

		const docStr = f.document.replace(/`/g, '\\`').replace(/\$/g, '\\$');

		if (clientPreset) {
			lines.push(`export const ${f.name}: TypedQueryString<${resultName}, Record<string, never>> =`);
			lines.push(`  createTypedQuery<${resultName}, Record<string, never>>(\`${docStr}\`);`);
		} else {
			lines.push(`export const ${f.name}: TypedDocumentNode<${resultName}, Record<string, never>> =`);
			lines.push(`  gql\`${docStr}\` as TypedDocumentNode<${resultName}, Record<string, never>>;`);
		}
		lines.push('');
	}

	return lines.join('\n');
}

export function generateFragmentIndex(fragments: ParsedFragment[]): string {
	const lines: string[] = ['// Auto-generated by @quenetiq/codegen. DO NOT EDIT.\n'];
	for (const f of fragments) {
		lines.push(`export { ${f.name}Fragment, ${f.name}Fragment\$key, ${f.name} } from "./${f.name}";`);
	}
	return lines.join('\n');
}

function extractTypeNames(code: string): string[] {
	const names = new Set<string>();
	const re = /^export\s+(interface|type|const enum|enum)\s+(\w+)/gm;
	let m;
	while ((m = re.exec(code)) !== null) names.add(m[2]);
	return Array.from(names).sort();
}
