import { readFileSync, existsSync } from 'fs';
import { globSync } from 'glob';
import {
	parse,
	type DocumentNode,
	type OperationDefinitionNode,
	type VariableDefinitionNode,
	type SelectionNode,
	type FieldNode,
	type FragmentSpreadNode,
	type InlineFragmentNode,
} from 'graphql';

export interface OperationVar {
	name: string;
	type: string;
}

export interface ParsedOperation {
	name: string;
	type: 'query' | 'mutation' | 'subscription';
	variables: OperationVar[];
	document: string;
	filePath: string;
}

export function findGraphqlFiles(pattern: string): string[] {
	return globSync(pattern, { absolute: true });
}

export function parseGraphqlFile(filePath: string): ParsedOperation | null {
	if (!existsSync(filePath)) return null;

	const content = readFileSync(filePath, 'utf-8').trim();
	if (!content) return null;

	let doc: DocumentNode;
	try {
		doc = parse(content);
	} catch {
		return null;
	}

	const def = doc.definitions.find((d): d is OperationDefinitionNode => d.kind === 'OperationDefinition');

	if (!def) return null;

	const name = def.name?.value;
	if (!name) return null;

	const variables: OperationVar[] = (def.variableDefinitions ?? []).map((v: VariableDefinitionNode) => {
		return {
			name: v.variable.name.value,
			type: printTypeRef(v.type),
		};
	});

	return {
		name,
		type: def.operation as 'query' | 'mutation' | 'subscription',
		variables,
		document: content,
		filePath,
	};
}

function printTypeRef(type: unknown): string {
	const wrap = (t: Record<string, unknown> | null): string => {
		if (!t) return '';
		if (t.kind === 'NonNullType') return `${wrap(t.type as Record<string, unknown>)}!`;
		if (t.kind === 'ListType') return `[${wrap(t.type as Record<string, unknown>)}]`;
		return (t.name as { value: string })?.value ?? '';
	};
	return wrap(type as Record<string, unknown>);
}

/** Extract type/interface/enum names from generated TS code */
function extractTypeNames(code: string): string[] {
	const names = new Set<string>();
	const re = /^export\s+(interface|type|const enum|enum)\s+(\w+)/gm;
	let m;
	while ((m = re.exec(code)) !== null) names.add(m[2]);
	return Array.from(names).sort();
}

export interface FragmentTypeInfo {
	name: string;
	keyName: string;
	typeCondition: string;
	importRelative: string;
}

export interface DocumentCodegenOptions {
	prefix?: string;
	suffix?: string;
	/** When true, generates `createTypedQuery()` instead of `gql` tag — skips runtime `parse()`. */
	clientPreset?: boolean;
}

/**
 * Walk a selection set and generate a TS type string.
 * Recursively handles fields, inline fragments, and fragment spreads.
 */
function generateSelectionType(
	selections: readonly SelectionNode[],
	fragmentTypes: Map<string, FragmentTypeInfo>,
	indent = 1,
): string {
	const props: string[] = [];
	const keyRefs: string[] = [];

	for (const sel of selections) {
		if (sel.kind === 'Field') {
			const f = sel as FieldNode;
			const name = f.name.value;
			const alias = f.alias?.value ?? name;
			if (name.startsWith('__')) continue;

			if (f.selectionSet && f.selectionSet.selections.length > 0) {
				const childType = generateSelectionType(f.selectionSet.selections, fragmentTypes, indent + 1);
				props.push(`${'  '.repeat(indent)}${alias}: ${childType};`);
			} else {
				props.push(`${'  '.repeat(indent)}${alias}: unknown;`);
			}
		} else if (sel.kind === 'InlineFragment') {
			const inf = sel as InlineFragmentNode;
			if (inf.selectionSet.selections.length > 0) {
				const childType = generateSelectionType(inf.selectionSet.selections, fragmentTypes, indent);
				if (inf.typeCondition) {
					props.push(`${'  '.repeat(indent)}{ __typename: '${inf.typeCondition.name.value}' } & (${childType})`);
				} else {
					keyRefs.push(childType);
				}
			}
		} else if (sel.kind === 'FragmentSpread') {
			const fs = sel as FragmentSpreadNode;
			const fi = fragmentTypes.get(fs.name.value);
			if (fi) {
				keyRefs.push(fi.keyName);
			}
		}
	}

	if (props.length === 0 && keyRefs.length === 0) return 'Record<string, unknown>';

	const allParts = [...keyRefs];
	if (props.length > 0) {
		allParts.push(`{\n${props.join('\n')}\n${'  '.repeat(indent - 1)}}`);
	}

	return allParts.join(' & ');
}

export function generateTypedDocumentsCode(
	operations: ParsedOperation[],
	schemaTypes?: string[] | string,
	options?: DocumentCodegenOptions,
	fragmentTypes?: Map<string, FragmentTypeInfo>,
): string {
	const typeNames = Array.isArray(schemaTypes) ? schemaTypes : schemaTypes ? extractTypeNames(schemaTypes) : [];

	const clientPreset = options?.clientPreset === true;
	const prefix = options?.prefix ?? '';
	const suffix = options?.suffix ?? '';

	const lines: string[] = ['// Auto-generated by @quenetiq/codegen. DO NOT EDIT.\n'];

	if (clientPreset) {
		lines.push('import { createTypedQuery, type TypedQueryString } from "@quenetiq/core";\n');
	} else {
		lines.push('import { gql, type TypedDocumentNode } from "@quenetiq/core";\n');
	}

	const fragImportNames = new Set<string>();
	if (fragmentTypes) {
		for (const op of operations) {
			const doc = parse(op.document);
			const def = doc.definitions.find((d): d is OperationDefinitionNode => d.kind === 'OperationDefinition');
			if (!def) continue;
			const used = collectFragmentSpreadNames(def.selectionSet.selections);
			used.forEach((n) => {
				const fi = fragmentTypes!.get(n);
				if (fi) fragImportNames.add(fi.importRelative);
			});
		}
	}

	if (fragImportNames.size > 0) {
		lines.push('import type {');
		const seen = new Set<string>();
		for (const relPath of fragImportNames) {
			if (!seen.has(relPath)) {
				seen.add(relPath);
				lines.push(`  ${relPath.replace(/.*\//, '').replace(/\.\.\//g, '')},`);
			}
		}
		lines.push('} from "../fragments/index";\n');
	}

	if (typeNames.length > 0) {
		lines.push('import type {');
		typeNames.forEach((t) => lines.push(`  ${t},`));
		lines.push('} from "../types";\n');
	}

	for (const op of operations) {
		const resultName = `${prefix}${op.name}${suffix}`;
		const varName = `${op.name}Variables`;
		const hasVars = op.variables.length > 0;

		if (hasVars) {
			lines.push(`export interface ${varName} {`);
			for (const v of op.variables) {
				lines.push(`  ${v.name}: ${v.type};`);
			}
			lines.push('}\n');
		}

		if (fragmentTypes) {
			const doc = parse(op.document);
			const def = doc.definitions.find((d): d is OperationDefinitionNode => d.kind === 'OperationDefinition');
			if (def) {
				const resultType = generateSelectionType(def.selectionSet.selections, fragmentTypes);
				lines.push(`export type ${resultName} = ${resultType};`);
				lines.push('');
			}
		}

		const varGeneric = hasVars ? varName : 'Record<string, never>';

		if (clientPreset) {
			const docStr = op.document.replace(/`/g, '\\`').replace(/\$/g, '\\$');
			lines.push(`export const ${op.name}: TypedQueryString<${resultName}, ${varGeneric}> =`);
			lines.push(`  createTypedQuery<${resultName}, ${varGeneric}>(\`${docStr}\`);`);
		} else {
			const docStr = op.document.replace(/`/g, '\\`');
			lines.push(`export const ${op.name}: TypedDocumentNode<${resultName}, ${varGeneric}> =`);
			lines.push(`  gql\`${docStr}\` as TypedDocumentNode<${resultName}, ${varGeneric}>;`);
		}
		lines.push('');
	}

	return lines.join('\n');
}

function collectFragmentSpreadNames(selections: readonly SelectionNode[]): Set<string> {
	const names = new Set<string>();
	for (const sel of selections) {
		if (sel.kind === 'FragmentSpread') {
			names.add((sel as FragmentSpreadNode).name.value);
		} else if (sel.kind === 'Field' && (sel as FieldNode).selectionSet) {
			const sub = collectFragmentSpreadNames((sel as FieldNode).selectionSet!.selections);
			sub.forEach((n) => names.add(n));
		} else if (sel.kind === 'InlineFragment') {
			const sub = collectFragmentSpreadNames((sel as InlineFragmentNode).selectionSet.selections);
			sub.forEach((n) => names.add(n));
		}
	}
	return names;
}

export function generateIndexCode(operations: ParsedOperation[]): string {
	const lines: string[] = ['// Auto-generated by @quenetiq/codegen. DO NOT EDIT.\n'];

	for (const op of operations) {
		lines.push(`export { ${op.name} } from "./${op.name}";`);
	}

	return lines.join('\n');
}
