import { writeFileSync } from 'fs';
import { mergeGeneratedTypes } from './schema-merge';

export interface TypeRef {
	base: string;
	nullable: boolean;
	list: boolean;
}

export type CodegenScalars = Record<string, string>;

export interface CodegenTypesConfig {
	scalars?: CodegenScalars;
	enumsAsTypes?: boolean;
	maybeValue?: string;
	operationResultPrefix?: string;
	operationResultSuffix?: string;
	/** When true, only appends new type definitions instead of rewriting the entire file. */
	merge?: boolean;
}

const builtinTypes = new Set([
	'String',
	'Int',
	'Float',
	'Boolean',
	'ID',
	'__Schema',
	'__Type',
	'__TypeKind',
	'__Field',
	'__InputValue',
	'__EnumValue',
	'__Directive',
	'__DirectiveLocation',
]);

function resolveRef(typeRef: Record<string, unknown>): TypeRef {
	let current = typeRef;
	let nullable = true;
	let list = false;
	while (current.ofType) {
		if (current.kind === 'NON_NULL') nullable = false;
		if (current.kind === 'LIST') list = true;
		current = current.ofType as Record<string, unknown>;
	}
	return { base: current.name as string, nullable, list };
}

function toTsType(typeRef: Record<string, unknown>, scalars: CodegenScalars): string {
	if (!typeRef) return 'unknown';
	const { base, nullable, list } = resolveRef(typeRef);
	if (builtinTypes.has(base)) {
		const mapping: Record<string, string> = {
			String: 'string',
			Int: 'number',
			Float: 'number',
			Boolean: 'boolean',
			ID: 'string',
		};
		let ts = mapping[base] || scalars[base] || base;
		if (list) ts = `${ts}[]`;
		return nullable ? `${ts} | null | undefined` : ts;
	}
	let ts = scalars[base] || base;
	if (list) ts = `${ts}[]`;
	return nullable ? `${ts} | null | undefined` : ts;
}

function isBuiltin(name: string): boolean {
	return builtinTypes.has(name) || name.startsWith('__');
}

export interface SchemaType {
	name: string;
	kind: string;
	fields?: Record<string, unknown>[];
	inputFields?: Record<string, unknown>[];
	enumValues?: Record<string, unknown>[];
	possibleTypes?: Record<string, unknown>[];
	interfaces?: Record<string, unknown>[];
}

export interface SchemaData {
	types: SchemaType[];
	queryType?: { name: string };
	mutationType?: { name: string };
	subscriptionType?: { name: string };
}

export function generateSchemaTypes(schema: SchemaData, config?: CodegenTypesConfig): string {
	const scalarsMap = config?.scalars || {};
	const enumsAsTypes = config?.enumsAsTypes ?? false;
	const lines: string[] = ['// Auto-generated by @quenetiq/codegen. DO NOT EDIT.\n'];

	const allTypes = schema.types.filter((t) => !isBuiltin(t.name));

	// Enums
	for (const t of allTypes) {
		if (t.kind !== 'ENUM') continue;
		if (enumsAsTypes) {
			lines.push(`export type ${t.name} =`);
			for (const v of t.enumValues || []) lines.push(`  | '${v.name}'`);
			lines.push(';');
		} else {
			lines.push(`export const enum ${t.name} {`);
			for (const v of t.enumValues || []) lines.push(`  ${v.name} = '${v.name}',`);
			lines.push('}');
		}
		lines.push('');
	}

	// Input objects
	for (const t of allTypes) {
		if (t.kind !== 'INPUT_OBJECT') continue;
		lines.push(`export interface ${t.name} {`);
		for (const f of t.inputFields || []) {
			const ts = toTsType(f.type as Record<string, unknown>, scalarsMap);
			lines.push(`  ${f.name as string}: ${ts};`);
		}
		lines.push('}');
		lines.push('');
	}

	// Objects and Interfaces
	for (const t of allTypes) {
		if (t.kind !== 'OBJECT' && t.kind !== 'INTERFACE') continue;
		lines.push(`export interface ${t.name} {`);
		for (const f of t.fields || []) {
			const ts = toTsType(f.type as Record<string, unknown>, scalarsMap);
			lines.push(`  ${f.name as string}: ${ts};`);
		}
		lines.push('}');
		lines.push('');
	}

	// Unions
	for (const t of allTypes) {
		if (t.kind !== 'UNION') continue;
		lines.push(`export type ${t.name} =`);
		for (const pt of t.possibleTypes || []) lines.push(`  | ${pt.name as string}`);
		lines.push(';');
		lines.push('');
	}

	// Root types
	if (schema.queryType) {
		lines.push(`export type Query = ${schema.queryType.name};`);
	}
	if (schema.mutationType) {
		lines.push(`export type Mutation = ${schema.mutationType.name};`);
	}
	if (schema.subscriptionType) {
		lines.push(`export type Subscription = ${schema.subscriptionType.name};`);
	}

	return lines.join('\n');
}

/**
 * Generates schema types and writes them to a file.
 * When {@link CodegenTypesConfig.merge} is true, only appends new definitions
 * to the existing file (preserving line positions of existing ones).
 */
export function generateSchemaFile(schema: SchemaData, outputPath: string, config?: CodegenTypesConfig): void {
	const typesCode = generateSchemaTypes(schema, config);

	if (config?.merge) {
		const { content } = mergeGeneratedTypes(outputPath, typesCode);
		writeFileSync(outputPath, content);
	} else {
		writeFileSync(outputPath, typesCode);
	}
}
