import { readFileSync, existsSync } from 'fs';

/**
 * Extracts all declared type names (interfaces, types, enums) from existing content.
 */
function extractExistingTypes(content: string): Set<string> {
	const types = new Set<string>();

	// export interface Foo
	const interfaceRe = /export\s+(interface|type|const\s+enum)\s+(\w+)/g;
	let match: RegExpExecArray | null;
	while ((match = interfaceRe.exec(content)) !== null) {
		types.add(match[2]);
	}

	// export type Foo = ... (union types)
	const typeRe = /export\s+type\s+(\w+)\s*=/g;
	while ((match = typeRe.exec(content)) !== null) {
		types.add(match[1]);
	}

	return types;
}

/**
 * Extracts individual type definitions from generated content.
 * Returns a map of type name -> definition block.
 */
function extractTypeDefinitions(content: string): Map<string, string> {
	const definitions = new Map<string, string>();

	// Match: export (interface|type|const enum) Name ... until next export or end
	const blockRe = /(export\s+(interface|type|const\s+enum)\s+(\w+)[^;]*?(?:;|\n(?=export)))/gs;
	let match: RegExpExecArray | null;
	while ((match = blockRe.exec(content)) !== null) {
		const name = match[3];
		const block = match[1].trim();
		definitions.set(name, block);
	}

	// Match union types: export type Name = ... ;
	const unionRe = /(export\s+type\s+(\w+)\s*=[^;]*?;)/gs;
	while ((match = unionRe.exec(content)) !== null) {
		const name = match[2];
		if (!definitions.has(name)) {
			definitions.set(name, match[1].trim());
		}
	}

	return definitions;
}

/**
 * Merges newly generated type definitions into existing file content.
 * - Existing definitions keep their line positions (no diff noise)
 * - Only genuinely new type definitions are appended
 * - Removed types stay in place (no breaking deletions)
 *
 * Returns the merged content.
 */
export function mergeGeneratedTypes(existingFilePath: string, newContent: string): string {
	const header = '// Auto-generated by @quenetiq/codegen. DO NOT EDIT.\n';

	if (!existsSync(existingFilePath)) {
		return newContent;
	}

	const existingContent = readFileSync(existingFilePath, 'utf-8');

	const existingTypes = extractExistingTypes(existingContent);
	const newDefinitions = extractTypeDefinitions(newContent);

	// Collect type names from new content for ordering reference
	const newOrder = extractTypeDefinitions(newContent);
	const orderedNames = Array.from(newOrder.keys());

	// Build merged content preserving existing structure
	const lines: string[] = [header];

	// Add existing type definitions in their original order
	const seen = new Set<string>();
	const existingLines = existingContent.split('\n');

	// Skip the header line from existing content
	let inHeader = true;
	let currentBlock: string[] = [];
	let currentName = '';

	for (const line of existingLines) {
		if (inHeader && (line.startsWith('// Auto-generated') || line.trim() === '')) {
			continue;
		}
		inHeader = false;

		const blockStartMatch = line.match(/^export\s+(interface|type|const\s+enum)\s+(\w+)/);
		const unionMatch = line.match(/^export\s+type\s+(\w+)\s*=/);

		if (blockStartMatch || unionMatch) {
			// Flush previous block
			if (currentName && currentBlock.length > 0) {
				if (seen.has(currentName) && existingTypes.has(currentName)) {
					lines.push(...currentBlock);
				}
				seen.add(currentName);
			}

			currentName = blockStartMatch?.[2] ?? unionMatch![1];
			currentBlock = [line];
		} else if (currentName) {
			currentBlock.push(line);
			// Check if this line ends the block (next export or empty line at top level)
			const trimmed = line.trim();
			if (trimmed === '}' || trimmed.endsWith('};') || trimmed.endsWith(';')) {
				// Check if next line starts a new export or it's the end
				// We'll decide at the next block start
			}
		} else if (line.trim()) {
			// Non-export lines (imports, root types like Query = ...)
			lines.push(line);
		}
	}

	// Flush last block
	if (currentName && currentBlock.length > 0 && !seen.has(currentName)) {
		if (existingTypes.has(currentName)) {
			lines.push(...currentBlock);
		}
		seen.add(currentName);
	}

	// Append genuinely new definitions
	const _addedCount = 0; // eslint-disable-line @typescript-eslint/no-unused-vars
	for (const name of orderedNames) {
		if (seen.has(name)) continue;

		const def = newDefinitions.get(name);
		if (def) {
			lines.push('');
			lines.push(def);
			addedCount++;
		}
	}

	const result = `${lines.join('\n')  }\n`;

	return result;
}
