import { parse, type DocumentNode, print } from 'graphql';

export function gql(strings: TemplateStringsArray, ...values: string[]): DocumentNode {
	return parse(String.raw(strings, ...values));
}

export { type DocumentNode, print };

export interface TypedDocumentNode<
	TResult = unknown,
	TVariables extends Record<string, unknown> = Record<string, unknown>,
> extends DocumentNode {
	__resultType?: TResult;
	__variablesType?: TVariables;
}

/**
 * A pre-serialized GraphQL query string with phantom types for result and variables.
 * Created by `createTypedQuery()`. Skips runtime `parse()` — ideal for production bundles
 * when using @quenetiq/codegen client preset.
 *
 * Usage:
 * ```typescript
 * import { createTypedQuery } from '@quenetiq/core';
 *
 * const GetNotes = createTypedQuery<GetNotesResult, GetNotesVariables>(
 *   'query GetNotes { getNotes { id title } }'
 * );
 * ```
 */
export type TypedQueryString<
	TResult = unknown,
	TVariables extends Record<string, unknown> = Record<string, unknown>,
> = string & {
	__resultType?: TResult;
	__variablesType?: TVariables;
};

/**
 * Creates a typed query string without runtime parsing.
 * Zero-cost abstraction — just returns the input string with type annotations.
 * Compatible with `GraphqlService.query()` and `GraphqlService.mutate()`.
 */
export function createTypedQuery<TResult, TVariables extends Record<string, unknown> = Record<string, unknown>>(
	query: string,
): TypedQueryString<TResult, TVariables> {
	return query as TypedQueryString<TResult, TVariables>;
}

/**
 * Fragment reference type for Relay-style fragment masking.
 * When a query spreads a fragment, the fragment's data is stored under a
 * namespaced key (` ${fragmentName}`) rather than inlined directly.
 * Only the owning component can unmask it via `useFragment()`.
 *
 * @example
 * ```typescript
 * // Generated by @quenetiq/codegen:
 * export type BookFieldsFragment = Pick<Book, 'id' | 'title'>;
 * export type BookFieldsFragment$key = FragmentRef<BookFieldsFragment, 'BookFields'>;
 *
 * // Parent query result:
 * type GetBooksResult = {
 *   books: Array<BookFieldsFragment$key>; // only ` BookFields` property visible
 * };
 *
 * // Child component:
 * const data = useFragment(BookFields, book);
 * // data: BookFieldsFragment — has `id` and `title`
 * ```
 */
export type FragmentRef<TData, TName extends string> = {
	readonly [K in TName as ` ${K}`]: TData;
};
